### ISSUE TITLE
Task for Harika -  Main page

### ISSUE THREAD

**Issue by tejaswinin5** [SaiTejaswiniNarne/GetVeggiesFruits-Android-Project#1]
Add an image view widget, add a text box to enter the store and add a button to search, just put a button giving the name as deals of the day

**Comment by harika-naidu135** [comment]
Added the Main Page to the app that has the listview of the veggies an fruits where the user can able to select from the list view, with the descriptions buttons of the veggies and fruits. with another 2 buttons 
1. Return - This button will navigate the user to move to the previous page.
2. Select and Proceed - The button will navigate the user to the next page with a selected list of items.
