### ISSUE TITLE
Task to sonam - Store Location

### ISSUE THREAD

**Issue by tejaswinin5** [SaiTejaswiniNarne/GetVeggiesFruits-Android-Project#3]
Should create a list view of locations where the delivery options are present so that the customer can know the different locations of the store and can avail special discounts on special days.

**Comment by SonamGadkari** [comment]
Worked on the StoreLayout and its activity. The app is running fine.

**Comment by SonamGadkari** [comment]
Data is populated correctly in Main activity.Hence closing the issue.
