### ISSUE TITLE
Task to Akshara - Billing information of the customer 

### ISSUE THREAD

**Issue by tejaswinin5** [SaiTejaswiniNarne/GetVeggiesFruits-Android-Project#4]
create a layout with a text view widget order information, ask to give details like customer name, customer address and pin code( a text view widget with “Customer Name” and an edit text widget with “Enter your name”). Also create a drop-down button(payment options) to choose cash on delivery, bank account, debit card, credit card using Spinner in the layout.

**Comment by AksharaGurram** [comment]
Completed the given task of creating the customer details and process is going on creating the listview for payment options i.e. card type.

**Comment by AksharaGurram** [comment]
spinner is

**Comment by AksharaGurram** [comment]
spinner should be added
